---
version: '3.7'

networks:
  mgmt-postgres:
    name: mgmt-postgres
    driver: bridge

volumes:
  mgmt-postgres-data:
    name: mgmt-postgres-data
  mgmt-postgres-pgadmin4-data:
    name: mgmt-postgres-pgadmin4-data

x-logging: &x-logging
  driver: 'json-file'
  options:
    max-file: '5'
    max-size: '15m'

services:
  postgres:
    image: postgres:latest
    container_name: mgmt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - mgmt-postgres
    volumes:
      - mgmt-postgres-data:/var/lib/postgresql/data
    logging: *x-logging

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: mgmt-postgres-pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}    
    ports:
      - 8080:80
    networks:
      - mgmt-postgres
    volumes:
      - mgmt-postgres-pgadmin4-data:/var/lib/pgadmin
    logging: *x-logging
